In [4]:
import pandas as pd

data = {
    "name": ["Amit","Neha","Raj","Sara","Kunal","Rohit","Priya","Arjun","Meera","Vikas","Pooja","Nikhil"],
    "city": ["Pune","Mumbai","Pune","Delhi","Pune","Mumbai","Delhi","Pune","Mumbai","Delhi","Pune","Mumbai"],
    "age": [22,25,23,26,24,28,27,21,29,30,22,26],
    "salary": [30000,45000,35000,50000,40000,52000,48000,31000,47000,51000,36000,53000]
}

df = pd.DataFrame(data)
df

      name    city  age  salary
0     Amit    Pune   22   30000
1     Neha  Mumbai   25   45000
2      Raj    Pune   23   35000
3     Sara   Delhi   26   50000
4    Kunal    Pune   24   40000
5    Rohit  Mumbai   28   52000
6    Priya   Delhi   27   48000
7    Arjun    Pune   21   31000
8    Meera  Mumbai   29   47000
9    Vikas   Delhi   30   51000
10   Pooja    Pune   22   36000
11  Nikhil  Mumbai   26   53000

In [15]:
#show all names in a single variable

df["city"]

0      Pune
1    Mumbai
2      Pune
3     Delhi
4      Pune
Name: city, dtype: str

In [17]:
# show multiple column names
df[["name", "city"]]

    name    city
0   Amit    Pune
1   Neha  Mumbai
2    Raj    Pune
3   Sara   Delhi
4  Kunal    Pune

In [18]:
#show rows where city = pune

df["city"] == "Pune"

0     True
1    False
2     True
3    False
4     True
Name: city, dtype: bool

In [19]:
df

    name    city  age  salary
0   Amit    Pune   22   30000
1   Neha  Mumbai   25   45000
2    Raj    Pune   23   35000
3   Sara   Delhi   26   50000
4  Kunal    Pune   24   40000

In [20]:
df["city"] == "Pune"

0     True
1    False
2     True
3    False
4     True
Name: city, dtype: bool

In [42]:
df[ (df["salary"]>40000) ]

   name    city  age  salary
1  Neha  Mumbai   25   45000
3  Sara   Delhi   26   50000

In [43]:
# show those rows where salary > 40000
df[df["salary"] > 40000]

   name    city  age  salary
1  Neha  Mumbai   25   45000
3  Sara   Delhi   26   50000

In [44]:
#2 conditions in a single query

df[ (df["city"]=="Pune") & (df["salary"]>35000) ]

    name  city  age  salary
4  Kunal  Pune   24   40000

In [48]:
#2 conditions with OR (|)

df[ (df["city"] == "Delhi") | (df["age"] <23) ]

   name   city  age  salary
0  Amit   Pune   22   30000
3  Sara  Delhi   26   50000

In [62]:
#Selecting columns after filtering

df.loc[ (df["city"] == "Pune"), ["name","city"] ]

    name  city
0   Amit  Pune
2    Raj  Pune
4  Kunal  Pune

In [67]:
#Selecting multiple columns after filtering

df.loc[df["salary"] >= 40000, ["name", "city"]]

    name    city
1   Neha  Mumbai
3   Sara   Delhi
4  Kunal    Pune

In [74]:
#Add a new column with values for each row
df["tax"] = df["age"] *0.10
df

    name    city  age  salary  tax
0   Amit    Pune   22   30000  2.2
1   Neha  Mumbai   25   45000  2.5
2    Raj    Pune   23   35000  2.3
3   Sara   Delhi   26   50000  2.6
4  Kunal    Pune   24   40000  2.4

In [78]:
#Getting a boolean mask
df["salary"] > 40000

0    False
1     True
2    False
3     True
4    False
Name: salary, dtype: bool

In [83]:
#Counting rows and columns in filtered dataset
df[ (df["city"] == "Pune") ].shape

(3, 5)

In [87]:
#unique values
df["city"].unique()

<StringArray>
['Pune', 'Mumbai', 'Delhi']
Length: 3, dtype: str

In [88]:
# count of each city
df["city"].value_counts()

city
Pune      3
Mumbai    1
Delhi     1
Name: count, dtype: int64

In [89]:
#group by 
df.groupby("city")["salary"].mean()

city
Delhi     50000.0
Mumbai    45000.0
Pune      35000.0
Name: salary, dtype: float64

In [13]:
df[ ( df["city"] == "Pune") ]

    name  city  age  salary
0   Amit  Pune   22   30000
2    Raj  Pune   23   35000
4  Kunal  Pune   24   40000

In [15]:
df

    name    city  age  salary
0   Amit    Pune   22   30000
1   Neha  Mumbai   25   45000
2    Raj    Pune   23   35000
3   Sara   Delhi   26   50000
4  Kunal    Pune   24   40000

In [19]:
#Group by - After groupby, you must apply an aggregation to get a result (like sum, mean, max, count, etc.)
df.groupby("city")["age"].max()

city
Delhi     26
Mumbai    25
Pune      24
Name: age, dtype: int64

In [21]:
#Group by - Multiple aggerations 
df.groupby("city")["salary"].agg(["mean", "max", "min"])

           mean    max    min
city
Delhi   50000.0  50000  50000
Mumbai  45000.0  45000  45000
Pune    35000.0  40000  30000

In [22]:
df.groupby("city").size()

city
Delhi     1
Mumbai    1
Pune      3
dtype: int64

In [23]:
df

    name    city  age  salary
0   Amit    Pune   22   30000
1   Neha  Mumbai   25   45000
2    Raj    Pune   23   35000
3   Sara   Delhi   26   50000
4  Kunal    Pune   24   40000

In [24]:
#Group by size
df.groupby("city").size()

city
Delhi     1
Mumbai    1
Pune      3
dtype: int64

In [27]:
#Groupby - total salary per city
df.groupby("city")["salary"].sum()

city
Delhi      50000
Mumbai     45000
Pune      105000
Name: salary, dtype: int64

In [28]:
#Order by ascending
df.sort_values("salary")

    name    city  age  salary
0   Amit    Pune   22   30000
2    Raj    Pune   23   35000
4  Kunal    Pune   24   40000
1   Neha  Mumbai   25   45000
3   Sara   Delhi   26   50000

In [29]:
#Order by descending
df.sort_values("salary", ascending=False)

    name    city  age  salary
3   Sara   Delhi   26   50000
1   Neha  Mumbai   25   45000
4  Kunal    Pune   24   40000
2    Raj    Pune   23   35000
0   Amit    Pune   22   30000

In [33]:
#Get first 2 highest salaries
df.sort_values("salary", ascending=False).head(2)

   name    city  age  salary
3  Sara   Delhi   26   50000
1  Neha  Mumbai   25   45000

In [36]:
#Smallest 2 salaries
df.nsmallest(2, "salary")

   name  city  age  salary
0  Amit  Pune   22   30000
2   Raj  Pune   23   35000

In [40]:
#largest 2 salaries
df.nlargest(2, "salary")

   name    city  age  salary
3  Sara   Delhi   26   50000
1  Neha  Mumbai   25   45000

In [18]:
#Oldest person in dataset
df.nlargest(1, "age")

    name   city  age  salary
9  Vikas  Delhi   30   51000

In [17]:
#sorting priority , city priority is greater than that of salary 
#hence salary priority is nested inside each city
df.sort_values(["city","salary"], ascending=[True, False])

      name    city  age  salary
9    Vikas   Delhi   30   51000
3     Sara   Delhi   26   50000
6    Priya   Delhi   27   48000
11  Nikhil  Mumbai   26   53000
5    Rohit  Mumbai   28   52000
8    Meera  Mumbai   29   47000
1     Neha  Mumbai   25   45000
4    Kunal    Pune   24   40000
10   Pooja    Pune   22   36000
2      Raj    Pune   23   35000
7    Arjun    Pune   21   31000
0     Amit    Pune   22   30000

In [67]:
# top 2 salaries from each city
df.sort_values(["city","salary"], ascending=[True, False]) \
.groupby("city") \
.head(2)

      name    city  age  salary
9    Vikas   Delhi   30   51000
3     Sara   Delhi   26   50000
11  Nikhil  Mumbai   26   53000
5    Rohit  Mumbai   28   52000
4    Kunal    Pune   24   40000
10   Pooja    Pune   22   36000

In [68]:
# bottom 2 salaries from each city
df.sort_values(["city","salary"], ascending=[True, True]) \
.groupby("city") \
.head(2)

    name    city  age  salary
6  Priya   Delhi   27   48000
3   Sara   Delhi   26   50000
1   Neha  Mumbai   25   45000
8  Meera  Mumbai   29   47000
0   Amit    Pune   22   30000
7  Arjun    Pune   21   31000

In [77]:
#maximum salary per city
df.groupby("city")["salary"].max()

city
Delhi     51000
Mumbai    53000
Pune      40000
Name: salary, dtype: int64

In [83]:
#highest salary per city using idx

#idxmax() returns the index of the max salary (not the salary value)
#df.loc uses those indexes to return the full rows
df.loc[ df.groupby("city")["salary"].idxmax() ]

      name    city  age  salary
9    Vikas   Delhi   30   51000
11  Nikhil  Mumbai   26   53000
4    Kunal    Pune   24   40000

In [84]:
#lowest salary per city using idx
df.loc[ df.groupby("city")["salary"].idxmin() ]

    name    city  age  salary
6  Priya   Delhi   27   48000
1   Neha  Mumbai   25   45000
0   Amit    Pune   22   30000

In [88]:
df.loc[2, "salary"]

np.int64(35000)

In [89]:
df.loc[2]

name        Raj
city       Pune
age          23
salary    35000
Name: 2, dtype: object

In [97]:
#Number of missing values per column
df.isnull().sum()

name      0
city      0
age       1
salary    1
dtype: int64

In [5]:
df

      name    city  age  salary
0     Amit    Pune   22   30000
1     Neha  Mumbai   25   45000
2      Raj    Pune   23   35000
3     Sara   Delhi   26   50000
4    Kunal    Pune   24   40000
5    Rohit  Mumbai   28   52000
6    Priya   Delhi   27   48000
7    Arjun    Pune   21   31000
8    Meera  Mumbai   29   47000
9    Vikas   Delhi   30   51000
10   Pooja    Pune   22   36000
11  Nikhil  Mumbai   26   53000

In [6]:
#create a missing salary and a missing age
df.loc[2, "salary"] = None   # Raj salary missing
df.loc[5, "age"] = None      # Rohit age missing

df

      name    city   age   salary
0     Amit    Pune  22.0  30000.0
1     Neha  Mumbai  25.0  45000.0
2      Raj    Pune  23.0      NaN
3     Sara   Delhi  26.0  50000.0
4    Kunal    Pune  24.0  40000.0
5    Rohit  Mumbai   NaN  52000.0
6    Priya   Delhi  27.0  48000.0
7    Arjun    Pune  21.0  31000.0
8    Meera  Mumbai  29.0  47000.0
9    Vikas   Delhi  30.0  51000.0
10   Pooja    Pune  22.0  36000.0
11  Nikhil  Mumbai  26.0  53000.0

In [8]:
df.isnull().sum()

name      0
city      0
age       1
salary    1
dtype: int64

In [23]:
#df_clean represents a clean df
df_clean = df.dropna()
df_clean

      name    city   age   salary
0     Amit    Pune  22.0  30000.0
1     Neha  Mumbai  25.0  45000.0
3     Sara   Delhi  26.0  50000.0
4    Kunal    Pune  24.0  40000.0
6    Priya   Delhi  27.0  48000.0
7    Arjun    Pune  21.0  31000.0
8    Meera  Mumbai  29.0  47000.0
9    Vikas   Delhi  30.0  51000.0
10   Pooja    Pune  22.0  36000.0
11  Nikhil  Mumbai  26.0  53000.0

In [27]:
df

      name    city   age   salary
0     Amit    Pune  22.0  30000.0
1     Neha  Mumbai  25.0  45000.0
2      Raj    Pune  23.0      NaN
3     Sara   Delhi  26.0  50000.0
4    Kunal    Pune  24.0  40000.0
5    Rohit  Mumbai   NaN  52000.0
6    Priya   Delhi  27.0  48000.0
7    Arjun    Pune  21.0  31000.0
8    Meera  Mumbai  29.0  47000.0
9    Vikas   Delhi  30.0  51000.0
10   Pooja    Pune  22.0  36000.0
11  Nikhil  Mumbai  26.0  53000.0

In [41]:
#calculate average salary
average_value = df["salary"].mean()
average_value

np.float64(43909.09090909091)

In [44]:
# Fill NaN values in the "salary" column with average_value
# This does NOT modify the original DataFrame unless reassigned or inplace=True is used
df["salary"].fillna(average_value)

0     30000.000000
1     45000.000000
2     43909.090909
3     50000.000000
4     40000.000000
5     52000.000000
6     48000.000000
7     31000.000000
8     47000.000000
9     51000.000000
10    36000.000000
11    53000.000000
Name: salary, dtype: float64

In [49]:
# Fill missing salary values with the mean and update the DataFrame
df["salary"] = df["salary"].fillna(average_value)

In [50]:
df

      name    city   age        salary
0     Amit    Pune  22.0  30000.000000
1     Neha  Mumbai  25.0  45000.000000
2      Raj    Pune  23.0  43909.090909
3     Sara   Delhi  26.0  50000.000000
4    Kunal    Pune  24.0  40000.000000
5    Rohit  Mumbai   NaN  52000.000000
6    Priya   Delhi  27.0  48000.000000
7    Arjun    Pune  21.0  31000.000000
8    Meera  Mumbai  29.0  47000.000000
9    Vikas   Delhi  30.0  51000.000000
10   Pooja    Pune  22.0  36000.000000
11  Nikhil  Mumbai  26.0  53000.000000

In [51]:
#age cam have outliers or extreme values
#like - 
# 22,30,23,50,24

In [52]:
median_age = df["age"].median()
median_age

np.float64(25.0)

In [57]:
# Fill null values in the 'age' column with the median age
df["age"] = df["age"].fillna(median_age)

In [58]:
#calculate how many null values per column
df.isnull().sum()

name      0
city      0
age       0
salary    0
dtype: int64

In [60]:
df.dtypes

name          str
city          str
age       float64
salary    float64
dtype: object

In [62]:
df

      name    city   age        salary
0     Amit    Pune  22.0  30000.000000
1     Neha  Mumbai  25.0  45000.000000
2      Raj    Pune  23.0  43909.090909
3     Sara   Delhi  26.0  50000.000000
4    Kunal    Pune  24.0  40000.000000
5    Rohit  Mumbai  25.0  52000.000000
6    Priya   Delhi  27.0  48000.000000
7    Arjun    Pune  21.0  31000.000000
8    Meera  Mumbai  29.0  47000.000000
9    Vikas   Delhi  30.0  51000.000000
10   Pooja    Pune  22.0  36000.000000
11  Nikhil  Mumbai  26.0  53000.000000

In [63]:
df.dtypes

name          str
city          str
age       float64
salary    float64
dtype: object

In [64]:
df["age"]= df["age"].astype(int)

In [65]:
df.dtypes

name          str
city          str
age         int64
salary    float64
dtype: object

In [66]:
df

      name    city  age        salary
0     Amit    Pune   22  30000.000000
1     Neha  Mumbai   25  45000.000000
2      Raj    Pune   23  43909.090909
3     Sara   Delhi   26  50000.000000
4    Kunal    Pune   24  40000.000000
5    Rohit  Mumbai   25  52000.000000
6    Priya   Delhi   27  48000.000000
7    Arjun    Pune   21  31000.000000
8    Meera  Mumbai   29  47000.000000
9    Vikas   Delhi   30  51000.000000
10   Pooja    Pune   22  36000.000000
11  Nikhil  Mumbai   26  53000.000000

In [67]:
df.loc[0, "city"] = " pune "
df.loc[1, "city"] = "MUMBAI"

In [68]:
df

      name    city  age        salary
0     Amit   pune    22  30000.000000
1     Neha  MUMBAI   25  45000.000000
2      Raj    Pune   23  43909.090909
3     Sara   Delhi   26  50000.000000
4    Kunal    Pune   24  40000.000000
5    Rohit  Mumbai   25  52000.000000
6    Priya   Delhi   27  48000.000000
7    Arjun    Pune   21  31000.000000
8    Meera  Mumbai   29  47000.000000
9    Vikas   Delhi   30  51000.000000
10   Pooja    Pune   22  36000.000000
11  Nikhil  Mumbai   26  53000.000000

In [69]:
df["city"].str.strip()

0       pune
1     MUMBAI
2       Pune
3      Delhi
4       Pune
5     Mumbai
6      Delhi
7       Pune
8     Mumbai
9      Delhi
10      Pune
11    Mumbai
Name: city, dtype: str

In [71]:
df["city"] = df["city"].str.strip()

In [72]:
df

      name    city  age        salary
0     Amit    pune   22  30000.000000
1     Neha  MUMBAI   25  45000.000000
2      Raj    Pune   23  43909.090909
3     Sara   Delhi   26  50000.000000
4    Kunal    Pune   24  40000.000000
5    Rohit  Mumbai   25  52000.000000
6    Priya   Delhi   27  48000.000000
7    Arjun    Pune   21  31000.000000
8    Meera  Mumbai   29  47000.000000
9    Vikas   Delhi   30  51000.000000
10   Pooja    Pune   22  36000.000000
11  Nikhil  Mumbai   26  53000.000000

In [75]:
#String operations - make every city name in lowercase
df["city"] = df["city"].str.lower()

In [74]:
df

      name    city  age        salary
0     Amit    pune   22  30000.000000
1     Neha  mumbai   25  45000.000000
2      Raj    pune   23  43909.090909
3     Sara   delhi   26  50000.000000
4    Kunal    pune   24  40000.000000
5    Rohit  mumbai   25  52000.000000
6    Priya   delhi   27  48000.000000
7    Arjun    pune   21  31000.000000
8    Meera  mumbai   29  47000.000000
9    Vikas   delhi   30  51000.000000
10   Pooja    pune   22  36000.000000
11  Nikhil  mumbai   26  53000.000000

In [76]:
# Ensure city names are standardized
# Avoid duplicates caused by extra spaces or inconsistent casing
# e.g., "mumbai", "  mumbai  ", "Mumbai"
df["city"].unique()

<StringArray>
['pune', 'mumbai', 'delhi']
Length: 3, dtype: str

In [77]:
#String operations - replacing city names
df["city"] = df["city"].replace("pune", "pune city")

In [78]:
df

      name       city  age        salary
0     Amit  pune city   22  30000.000000
1     Neha     mumbai   25  45000.000000
2      Raj  pune city   23  43909.090909
3     Sara      delhi   26  50000.000000
4    Kunal  pune city   24  40000.000000
5    Rohit     mumbai   25  52000.000000
6    Priya      delhi   27  48000.000000
7    Arjun  pune city   21  31000.000000
8    Meera     mumbai   29  47000.000000
9    Vikas      delhi   30  51000.000000
10   Pooja  pune city   22  36000.000000
11  Nikhil     mumbai   26  53000.000000

In [83]:
#String operations - replacing multipe city names
df["city"] = df["city"].replace({
    "pune": "pune city",
    "delhi": "delhi ncr"
})

In [84]:
df

      name       city  age        salary
0     Amit  pune city   22  30000.000000
1     Neha     mumbai   25  45000.000000
2      Raj  pune city   23  43909.090909
3     Sara  delhi ncr   26  50000.000000
4    Kunal  pune city   24  40000.000000
5    Rohit     mumbai   25  52000.000000
6    Priya  delhi ncr   27  48000.000000
7    Arjun  pune city   21  31000.000000
8    Meera     mumbai   29  47000.000000
9    Vikas  delhi ncr   30  51000.000000
10   Pooja  pune city   22  36000.000000
11  Nikhil     mumbai   26  53000.000000

In [86]:
#Which row contains the word city ?
df[ df["city"].str.contains("city") ]

     name       city  age        salary
0    Amit  pune city   22  30000.000000
2     Raj  pune city   23  43909.090909
4   Kunal  pune city   24  40000.000000
7   Arjun  pune city   21  31000.000000
10  Pooja  pune city   22  36000.000000

In [87]:
df.loc[0, "city"] = "Pune City"
df.loc[1, "city"] = "mumbai CITY"
df.loc[2, "city"] = "Delhi ncr"
df.loc[3, "city"] = "pune city"

In [88]:
df

      name         city  age        salary
0     Amit    Pune City   22  30000.000000
1     Neha  mumbai CITY   25  45000.000000
2      Raj    Delhi ncr   23  43909.090909
3     Sara    pune city   26  50000.000000
4    Kunal    pune city   24  40000.000000
5    Rohit       mumbai   25  52000.000000
6    Priya    delhi ncr   27  48000.000000
7    Arjun    pune city   21  31000.000000
8    Meera       mumbai   29  47000.000000
9    Vikas    delhi ncr   30  51000.000000
10   Pooja    pune city   22  36000.000000
11  Nikhil       mumbai   26  53000.000000

In [93]:
#case sensitive variant
#only allow city , rest all are not allowed 
df[df["city"].str.contains("city")]

     name       city  age   salary
3    Sara  pune city   26  50000.0
4   Kunal  pune city   24  40000.0
7   Arjun  pune city   21  31000.0
10  Pooja  pune city   22  36000.0

In [94]:
#case insensitive variant
#allow city,City, citY etc
df[df["city"].str.contains("city", case=False)]

     name         city  age   salary
0    Amit    Pune City   22  30000.0
1    Neha  mumbai CITY   25  45000.0
3    Sara    pune city   26  50000.0
4   Kunal    pune city   24  40000.0
7   Arjun    pune city   21  31000.0
10  Pooja    pune city   22  36000.0

In [95]:
#new table for learning Merging tables
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "name": ["Amit", "Neha", "Raj", "Sara", "Kunal"],
    "amount": [5000, 7000, 3000, 9000, 6500]
})

orders

   order_id   name  amount
0       101   Amit    5000
1       102   Neha    7000
2       103    Raj    3000
3       104   Sara    9000
4       105  Kunal    6500

In [96]:
df

      name         city  age        salary
0     Amit    Pune City   22  30000.000000
1     Neha  mumbai CITY   25  45000.000000
2      Raj    Delhi ncr   23  43909.090909
3     Sara    pune city   26  50000.000000
4    Kunal    pune city   24  40000.000000
5    Rohit       mumbai   25  52000.000000
6    Priya    delhi ncr   27  48000.000000
7    Arjun    pune city   21  31000.000000
8    Meera       mumbai   29  47000.000000
9    Vikas    delhi ncr   30  51000.000000
10   Pooja    pune city   22  36000.000000
11  Nikhil       mumbai   26  53000.000000

In [97]:
orders

   order_id   name  amount
0       101   Amit    5000
1       102   Neha    7000
2       103    Raj    3000
3       104   Sara    9000
4       105  Kunal    6500

In [98]:
pd.merge(df,orders, on="name")

    name         city  age        salary  order_id  amount
0   Amit    Pune City   22  30000.000000       101    5000
1   Neha  mumbai CITY   25  45000.000000       102    7000
2    Raj    Delhi ncr   23  43909.090909       103    3000
3   Sara    pune city   26  50000.000000       104    9000
4  Kunal    pune city   24  40000.000000       105    6500